graph TD
    Kh_i__a_di_n_md["Khối đa diện"]
    S__ph_c_md["Số phức"]
    Ph__ng_ph_p_t_a____trong_kh_ng_gian_md["Phương pháp tọa độ trong không gian"]
    H_m_s__l_y_th_a__h_m_s__m__v__h_m_s__logarit_md["Hàm số lũy thừa, hàm số mũ và hàm số logarit"]
    Nguy_n_h_m__T_ch_ph_n_v___ng_d_ng_md["Nguyên hàm, Tích phân và Ứng dụng"]
    M_t_n_n__M_t_tr___M_t_c_u_md["Mặt nón, Mặt trụ, Mặt cầu"]
    MOC["MOC"]
    H_nh_h_c_12["Hình_học_12"]
    Gi_i_t_ch_12["Giải_tích_12"]
    Kh_i__a_di_n_md --> MOC
    Kh_i__a_di_n_md --> H_nh_h_c_12
    S__ph_c_md --> MOC
    S__ph_c_md --> Gi_i_t_ch_12
    Ph__ng_ph_p_t_a____trong_kh_ng_gian_md --> MOC
    Ph__ng_ph_p_t_a____trong_kh_ng_gian_md --> H_nh_h_c_12
    H_m_s__l_y_th_a__h_m_s__m__v__h_m_s__logarit_md --> MOC
    H_m_s__l_y_th_a__h_m_s__m__v__h_m_s__logarit_md --> Gi_i_t_ch_12
    Nguy_n_h_m__T_ch_ph_n_v___ng_d_ng_md --> MOC
    Nguy_n_h_m__T_ch_ph_n_v___ng_d_ng_md --> Gi_i_t_ch_12
    M_t_n_n__M_t_tr___M_t_c_u_md --> MOC
    M_t_n_n__M_t_tr___M_t_c_u_md --> H_nh_h_c_12
